### ISSUE TITLE
Failed to get an associated pull request

### ISSUE THREAD

**Issue by rrreeeyyy** [suzuki-shunsuke/ci-info#734]
Hello, I've been using ci-info through tfaction. Since upgrading to ci-info v2.2.0, commenting on merged PRs has stopped working properly. I'm encountering the following error:

- It might be noise, but I'll post the full actions log.
- I've replaced the GitHub owner with OWNER and the repo with REPO, but they are filled with the actual values used.
- It appears to be failing to retrieve a pull request like pulls/0.
- We do not use a merge queue in this environment.

```
time="2024-07-14T04:38:43Z" level=info msg="download and unarchive the package" aqua_version=2.29.0 env=linux/amd64 exe_name=ci-info package_name=suzuki-shunsuke/ci-info package_version=v2.2.0 program=aqua registry=standard
time="2024-07-14T04:38:43Z" level=info msg="verify a package with slsa-verifier" aqua_version=2.29.0 env=linux/amd64 exe_name=ci-info package_name=suzuki-shunsuke/ci-info package_version=v2.2.0 program=aqua registry=standard
Verified signature against tlog entry index 111615261 at URL: https://rekor.sigstore.dev/api/v1/log/entries/24296fb24b8ad77a0751df7a540f50d9a599d57ee059426e5bbedc09e8116fdd4ab116ff05442c8d
Verified build using builder "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v2.0.0" at commit 458eeb5db3c1eed805f98a6917da7e8c66f512a7
Verifying artifact /tmp/047521249: PASSED

PASSED: Verified SLSA provenance
time="2024-07-14T04:38:44Z" level=fatal msg="get an associated pull request: get a pull request: GET https://api.github.com/repos/OWNER/REPO/pulls/0: 404 Not Found []"
```

I will also look into the source code to investigate the cause, but I wanted to file this issue promptly.

Please feel free to mention if any additional information is needed or if it would be better to file this issue under the tfaction repository instead.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!
I'll take a look.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/ci-info/pull/735

**Comment by suzuki-shunsuke** [comment]
v2.2.1 is out 🎉
https://github.com/suzuki-shunsuke/ci-info/releases/tag/v2.2.1

**Comment by rrreeeyyy** [comment]
Thank you! That was incredibly fast. I've confirmed that it works correctly with v2.2.1.
